config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # devise_for :users #devise幫你長出來的 會自動對應該對應的controller

  # 有自己生成controller（rails g devise:controllers 資料夾名稱），客製化的部分要來此設定
  devise_for :users, controllers: {
    registrations: 'users/registrations' # 有關會員註冊（註冊及編輯資料）的controller 請使用users資料夾下的registrations_controlle.rb
  }

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # 首頁：不分類所有已發佈文章列表
  # Defines the root path route ("/")
  root "pages#index"

  # 文章CRUD
  resources :posts do
    # 文章留言
    # /posts/:post_id/comments/:id
    resources :comments, only: [:create, :edit, :update, :destroy]
    # post_comments     POST   /posts/:post_id/comments(.:format)                  comments#create
    # edit_post_comment GET    /posts/:post_id/comments/:id/edit(.:format)         comments#edit
    # post_comment      PATCH  /posts/:post_id/comments/:id(.:format)              comments#update
    #                   PUT    /posts/:post_id/comments/:id(.:format)              comments#update
    # post_comment      DELETE /posts/:post_id/comments/:id(.:format)              comments#destroy
  end

  # 單篇文章頁面
  # /@ID/文章標題-123
  # post_page    GET    /@:username/:post_id(.:format)        pages#show
  get '@:username/:post_id', to: 'pages#show', as: 'post_page'
  # prefix設定為 post_page（不設定就沒有prefix可以用）
  # 不想額外生一個controller，所以就指定用pages controller
  # :username 是符號，冒號不會出現在網址

  # 單一使用者文章列表
  # /@ID
  # user_page   GET    /@:username(.:format)           pages#user
  get '@:username', to: 'pages#user', as: 'user_page'

  # 熱門文章
  # hot_page   GET    /hot(.:format)              pages#hot
  get 'hot', to: 'pages#hot', as: 'hot_page'

  # 創作者排行榜
  # rank_page   GET    /rank(.:format)      pages#rank
  get 'rank', to: 'pages#rank', as: 'rank_page'

  # api相關路徑
  namespace :api do
    namespace :v1 do

      # 追蹤使用者功能 的 api
      # follow_api_v1_user    POST   /api/v1/users/:id/follow(.:format)       api/v1/users#follow
      resources :users, only: [] do
      # 想要網址帶users 但users的CRUD都被devise做完，所以這裡給空陣列，單純用來生成 追蹤使用者功能 的 api路徑
        member do
          post :follow
        end
      end

      resources :posts, only: [] do
        member do
          # 為文章按愛心功能 的 api
          # love_api_v1_post   POST   /api/v1/posts/:id/love(.:format)    api/v1/posts#love
          post :love
          # 收藏文章功能 的 api
          # bookmark_api_v1_post    POST   /api/v1/posts/:id/bookmark(.:format)      api/v1/posts#bookmark
          post :bookmark
        end
      end

      # 用Froala editor上傳圖片功能 的 api
      # api_v1_upload_image    POST   /api/v1/upload_image(.:format)        api/v1/utils#upload_image
      post :upload_image, to: 'utils#upload_image'

    end
  end

  namespace :my do
    # 個人資料首頁：我的收藏
    # my_root   GET    /my(.:format     my/profile#collections
    root 'profiles#collections'
    # 我的收藏
    # my_collections_page    GET    /my/collections(.:format)           my/profile#collections
    get 'collections', to: 'profiles#collections', as: 'collections_page'
    # 我的追蹤的使用者
    # my_following_page   GET    /my/following(.:format)            my/profile#following
    get 'following', to: 'profiles#following', as: 'following_page'
  end
  
end

app/models/post.rb
# $ rails g model Post title content:text status user:references

class Post < ApplicationRecord

  # 有限狀態機套件
  include AASM

  # 友善ID套件
  extend FriendlyId
  # friendly_id :給friendly id 用的slug, use: :slugged
  friendly_id :slug_post , use: :slugged

  # 軟刪除套件
  acts_as_paranoid
  # 覆寫destroy方法
  # 增加預設搜尋條件
  # destroy後rails c看不到，但尚存在於資料庫

  # 表單送出後 寫進資料庫前 之 後端驗證
  validates :title, presence: true
  
  # 資料間關聯
  belongs_to :user
  # 動態長出 user 與 user= 方法
  has_many :comments, dependent: :destroy # 刪除一篇文章，其相關的留言也需要被刪除，否則它們只會佔用資料庫空間
  # 動態長出 comments comments= build create 方法
  has_many :bookmarks, dependent: :destroy
  # 動態長出 bookmarks bookmarks= build create 方法
  has_one_attached :cover_image
  # 每篇文章都可以有一個封面照片
  # Active Storage

  # 搜尋條件範圍
  scope :published_posts, -> { where(status: 'published') }
  # 按 建立順序 顯示的 已發佈文章
  scope :published_posts_created_at, -> { published.with_attached_cover_image.order(created_at: :desc).includes(:user) }
  # published為aasm送的方法，能撈出所有 狀態欄位 值 為published的文章

  # 按 愛心數順序 顯示的 已發佈文章
  scope :published_posts_love, -> { published.with_attached_cover_image.order(love: :desc).includes(:user) }
  

  # 實體方法
  def bookmark?(user) # 文章 有無被 某user 收藏  # 作用在 文章實體 上 的 實體方法
    bookmarks.exists?(user: user)
    # 在bookmarks表格中 傳進來的參數user 是否存在於 user_id欄位 中
    # 回傳布林值
  end

  def bookmark!(user) # 被user收藏或取消收藏
    # 到資料表改資料
    if bookmark?(user) # 已經被收藏->取消收藏
      bookmarks.find_by(user: user).destroy
      # 找到bookmarks資料表中 user_id欄位值 為 傳入之參數user 的資料 並刪除
      return '已被取消收藏'
    else # 還沒被收藏->被收藏
      bookmarks.create(user: user)
      return '已被收藏'
    end
  end

  def normalize_friendly_id(input) # babosa方法 轉換文字編碼
    input.to_s.to_slug.normalize(transliterations: :russian).to_s
  end
  # http://localhost:3000/posts/文章中文標題/edit

  
  aasm(column: 'status', no_direct_assignment: true) do 
  # 預設會去找aasm_state欄位 以(column: 'status')更改預設
  # 不允許直接更動欄位值 只能透過狀態機轉換方法改
    state :draft, initial: true # 初始狀態
    state :published

    event :publish do # 發佈文章
      transitions from: :draft, to: :published
      # after do
      #   puts "發簡訊通知"
      # end
    end

    event :unpublish do # 下架文章
      transitions from: :published, to: :draft
    end

  end
  # 長出方法
  # draft? published? may_publish? may_unpublish? publish! unpublish!

  private

  def slug_post # 文章 給friendly id 用的slug
    [
      :title, # 文章標題
      [:title, SecureRandom.hex[0, 8]] # 為同名文章產生 另外 的 網址編號
    ]
  end
  # http://localhost:3000/posts/文章標題-b3e5f0e8/edit


end

app/controllers/api/v1/posts_controller.rb
# $ rails g controller posts

class Api::V1::PostsController < Api::V1::BaseController

    before_action :find_post

    def love # 為文章按愛心功能 api
    # love_api_v1_post   POST   /api/v1/posts/:id/love(.:format)    api/v1/posts#love

        # 先找到按哪篇文章的愛心（before action 已做）

        @post.increment!(:love)
        # 將posts資料表love欄位的值+1
        # increment! 驚嘆號 直接寫進資料庫 不用save兩段式
        render json: {status: @post.love} # 要傳給前端controller的資料（json格式）

    end

    def bookmark # 收藏文章功能 api
    # bookmark_api_v1_post    POST   /api/v1/posts/:id/bookmark(.:format)      api/v1/posts#bookmark

        # 先找到要收藏哪篇文章（before action 已做）

        # 讓 文章 被 當前使用者 收藏
        render json: {status: @post.bookmark!(current_user), count: @post.bookmarks.count} # 要傳給前端controller的資料（json格式）
    end

    private

    def find_post
        @post = Post.friendly.find(params[:id])
    end

end

app/controllers/posts_controller.rb
# $ rails g controller posts

class PostsController < ApplicationController

    # 驗證使用者有登入 才能用post相關頁面 不然就踢到登入頁面
    before_action :authenticate_user!

    before_action :find_post, only: [:edit, :update, :destroy]
    # rails 7.1後only except裡面不能寫還沒寫的action，但可以改變設定：`config.action_controller.raise_on_missing_callback_actions` to `false`.

    def index
        @posts = current_user.posts.order(created_at: :desc)
    end

    def new # 建立文章表單頁面 對應的動作
        @post = current_user.posts.new
    end

    def create # 送出建立文章表單
        @post = current_user.posts.new(post_params)
        @post.publish! if params[:publish] 
        # post model已設定no_direct_assignment: true 所以不能直接改欄位值 要用aasm的方法
        # params hash中有:publish這個key的話（若使用者按發佈按鈕，就會讓params hash中有:publish這個key） 就將posts資料表status欄位值指定為published
        # 文章status欄位預設值為draft，所以不用寫該情況

        if @post.save
            # 新增文章頁面 發佈 與 儲存為草稿 按鈕 之流程判斷
            if params[:publish] # 若按下 發佈按鈕
                redirect_to posts_path, notice: '文章發佈成功'
            else # 若按下 儲存按鈕
                redirect_to edit_post_path(@post), notice: '文章已儲存為草稿'
            end 
        else
            render :new, status: :unprocessable_entity # 否則，動作會重新顯示表單，方法是使用狀態碼 422 無法處理的實體 呈現 app/views/articles/new.html.erb。
        end
    end

    def edit
    end
    
    def update

        if @post.update(post_params) # 若 成功更新文章
            # 編輯文章頁面 發佈、下架文章 與 儲存為草稿 按鈕 之流程判斷
            case
            when params[:publish] # 若按下 發佈按鈕
                @post.publish!
                redirect_to posts_path, notice: '文章已發佈'
            when params[:unpublish] # 若按下 文章下架按鈕
                @post.unpublish!
                redirect_to posts_path, notice: '文章已下架'
            else # 若按下 儲存按鈕
                redirect_to edit_post_path(@post), notice: '文章已儲存'
            end
        else # 寫入資料庫失敗
            render :edit, status: :unprocessable_entity # 重新顯示表單（包含錯誤訊息），方法是使用狀態碼 422 無法處理的實體 呈現 app/views/articles/edit.html.erb
        end

    end

    def destroy
        @post.destroy # 使用paranoia套件後，此處的destroy方法 已經 不會把資料直接從資料庫 抹除
        redirect_to posts_path, notice: '文章已刪除', status: :see_other
        # destroy 動作會從資料庫中擷取文章（before action），並呼叫 destroy。然後，它會將瀏覽器重新導向到 文章列表頁，狀態碼為 303 另尋他處。
    end

    private
    def post_params # 資料清洗
        params.require(:post).permit(:title, :content, :cover_image)
    end

    def find_post
        @post = current_user.posts.friendly.find(params[:id])
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/shared/_form.html.erb
<% if post.errors.any? %> <!-- 如果有任何錯誤訊息 -->
    <div class="notification is-danger mb-0 text-white">
        <%= post.errors.full_messages.to_sentence %>
    </div>
<% end %>

<div class="max-w-screen-md m-auto mb-2">
    <article class="media mt-5">
        <figure class="media-left">
            <!-- 有上傳頭貼 顯示上傳的頭貼，沒頭貼 顯示灰頭 -->
            <!-- <img src="https://fakeimg.pl/50x50/" class="avatar"> -->
            <% if current_user.avatar.attached? %>
                <%= image_tag current_user.avatar.variant(resize_to_fill: [50, 50]), class: 'avatar' %>
            <% else %>
                <i class="fa-solid fa-circle-user text-gray-500 text-5xl"></i>
            <% end %>
        </figure>
    
        <div class="media-content">
            <!-- ID -->
            <span class="text-gray-600">@<%= current_user.username %></span>
            <!-- 有卡稱 顯示卡稱，沒卡稱 就不顯示 -->
            <span>
                <% if current_user.cardname !=nil %>
                    <span>・<%= current_user.cardname %></span>
                <% else %>
                <% end %>
            </span>
            <p class="text-gray-400 text-sm mb-1.5"><%= Time.current.strftime("%Y年%m月%d日 %I:%M") %></p>
            <!-- https://khiav223577.github.io/blog/2018/03/03/Rails-%E4%B8%AD%E5%B8%B8%E6%90%9E%E6%B7%B7%E7%9A%84%E6%99%82%E5%8D%80%E5%95%8F%E9%A1%8C-Time-now-vs-Time-current/ -->
            <!-- Time.now 使用當前機器作業系統的時區；Time.current 使用 Rails 中設定的時區 -->
        </div>
    </article>
    
    <div class="mb-5">
        <!-- 建立表單之前 先建model -->
        <%= form_for(post, html: {class: 'post-editor'}) do |form| %>
            <div class="field">
                <%= image_tag post.cover_image.variant(resize_to_fit: [500, 300]), class:'mb-4 w-fit mx-auto' if post.cover_image.attached? %>
                <!-- 將影像縮放至符合指定尺寸，同時保留原始長寬比。如果影像大於指定尺寸，將縮小影像；如果小於，則放大影像。 -->
                <%= form.label :cover_image, '封面照片', class:'text-xl font-bold' %><span class="text-xl mr-3">（選填）</span>
                <%= form.file_field :cover_image, type: 'file' %>
            </div>
            <div class="field">
                <%= form.text_field :title, placeholder: "標題", class: 'input my-4 text-2xl' %>
            </div>
            <div class="field">
                <%= form.text_area :content, placeholder: "敘述", rows: '20', cols: '10', class: 'textarea' %>
            </div>
            <div class="text-right">
                <% if post.may_publish? %> <!-- 文章狀態為 可以發佈時（現為草稿） -->
                    <%= form.submit '儲存', name: 'save_as_draft', class: 'button bg-zinc-200'%>
                    <!-- Parameters: {"authenticity_token"=>"[FILTERED]", "post"=>{"title"=>"第一篇文章", "content"=>"第一篇文章內文第一篇文章內文第一篇文章內文第一篇文章內文第一篇文章內文第一篇文章內文第一篇文章內文第一篇文章內文第一篇文章內文第一篇文章內文第一篇文章內文"}, "save_as_draft"=>"儲存為草稿", "id"=>"1"} -->
                    <!-- paramseters hash中 有 "save_as_draft（key）"=>"儲存為草稿（value）" -->
                    <%= form.submit '發佈文章', name: 'publish', class: 'button bgc-light-blue text-white' if post.may_publish? %>
                <% else %> <!-- 文章狀態非 可以發佈時（現為已發佈） -->
                    <%= form.submit '下架文章', name: 'unpublish', class: 'button bg-zinc-200' if post.may_unpublish? %>
                    <%= form.submit '儲存', name: 'save_as_draft', class: 'button bgc-light-blue text-white'%>
                <% end %>
            </div>
        <% end %>
    </div> 

</div>

    
    

app/views/posts/shared/_profile-left.html.erb
<section class="column is-3">
    <div class="w-fit m-auto">
        <!-- <img src="https://fakeimg.pl/100x100/" class="avatar my-5"> -->
        <div class="avatar my-5">
            <% if current_user.avatar.attached? %>
                <%= image_tag current_user.avatar.variant(resize_to_fill: [100, 100]), class: 'avatar' %>
            <% else %>
                <i class="fa-solid fa-circle-user text-white text-8xl"></i>
            <% end %>
        </div>
    </div>

    <!-- 有卡稱 顯示卡稱+ID，沒卡稱 就只顯示ID -->
    <% if current_user.cardname != nil %>
        <p class="text-white text-2xl font-semibold text-center mb-1"><%= link_to current_user.cardname, user_page_path(current_user.username) %></p>
        <p class="text-gray-400 text-center mb-4">@<%= link_to current_user.username, user_page_path(current_user.username)%></p>
    <% else %>
        <p class="text-white text-2xl font-semibold text-center mb-4">@<%= link_to current_user.username, user_page_path(current_user.username)%></p>
    <% end %>

    <div class="w-fit mx-auto">
        <%= link_to my_collections_page_path do %>
            <i class="fa-solid fa-bookmark text-sky-600 text-xl ml-0.5 mr-2.5 mb-3"></i>
            <span class="text-white">我的收藏</span>
        <% end %><br>
        <%= link_to my_following_page_path do %>
            <i class="fa-solid fa-heart text-rose-500 text-xl mr-1.5 mb-3"></i>
            <span class="text-white">我追蹤的使用者</span>
        <% end %><br>
        <%= link_to posts_path do %>
            <i class="fa-solid fa-square-pen text-sky-600 text-xl mr-2 mb-3"></i>
            <span class="text-white">我的文章</span>
        <% end %><br>
        <%= link_to edit_user_registration_path do %>
            <i class="fa-solid fa-gear text-white text-xl mr-1.5 mb-3 "></i>
            <span class="text-white">我的個人資料</span>
        <% end %>
    </div>
</section>