config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # devise_for :users #devise幫你長出來的 會自動對應該對應的controller

  # 有自己生成controller（rails g devise:controllers 資料夾名稱），客製化的部分要來此設定
  devise_for :users, controllers: {
    registrations: 'users/registrations' # 有關會員註冊（註冊及編輯資料）的controller 請使用users資料夾下的registrations_controlle.rb
  }

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # 首頁：不分類所有已發佈文章列表
  # Defines the root path route ("/")
  root "pages#index"

  # 文章CRUD
  resources :posts do
    # 文章留言
    # /posts/:post_id/comments/:id
    resources :comments, only: [:create, :edit, :update, :destroy]
    # post_comments     POST   /posts/:post_id/comments(.:format)                  comments#create
    # edit_post_comment GET    /posts/:post_id/comments/:id/edit(.:format)         comments#edit
    # post_comment      PATCH  /posts/:post_id/comments/:id(.:format)              comments#update
    #                   PUT    /posts/:post_id/comments/:id(.:format)              comments#update
    # post_comment      DELETE /posts/:post_id/comments/:id(.:format)              comments#destroy
  end

  # 單篇文章頁面
  # /@ID/文章標題-123
  # post_page    GET    /@:username/:post_id(.:format)        pages#show
  get '@:username/:post_id', to: 'pages#show', as: 'post_page'
  # prefix設定為 post_page（不設定就沒有prefix可以用）
  # 不想額外生一個controller，所以就指定用pages controller
  # :username 是符號，冒號不會出現在網址

  # 單一使用者文章列表
  # /@ID
  # user_page   GET    /@:username(.:format)           pages#user
  get '@:username', to: 'pages#user', as: 'user_page'

  # 熱門文章
  # hot_page   GET    /hot(.:format)              pages#hot
  get 'hot', to: 'pages#hot', as: 'hot_page'

  # 創作者排行榜
  # rank_page   GET    /rank(.:format)      pages#rank
  get 'rank', to: 'pages#rank', as: 'rank_page'

  # api相關路徑
  namespace :api do
    namespace :v1 do

      # 追蹤使用者功能 的 api
      # follow_api_v1_user    POST   /api/v1/users/:id/follow(.:format)       api/v1/users#follow
      resources :users, only: [] do
      # 想要網址帶users 但users的CRUD都被devise做完，所以這裡給空陣列，單純用來生成 追蹤使用者功能 的 api路徑
        member do
          post :follow
        end
      end

      resources :posts, only: [] do
        member do
          # 為文章按愛心功能 的 api
          # love_api_v1_post   POST   /api/v1/posts/:id/love(.:format)    api/v1/posts#love
          post :love
          # 收藏文章功能 的 api
          # bookmark_api_v1_post    POST   /api/v1/posts/:id/bookmark(.:format)      api/v1/posts#bookmark
          post :bookmark
        end
      end

      # 用Froala editor上傳圖片功能 的 api
      # api_v1_upload_image    POST   /api/v1/upload_image(.:format)        api/v1/utils#upload_image
      post :upload_image, to: 'utils#upload_image'

    end
  end

  namespace :my do
    # 個人資料首頁：我的收藏
    # my_root   GET    /my(.:format     my/profile#collections
    root 'profiles#collections'
    # 我的收藏
    # my_collections_page    GET    /my/collections(.:format)           my/profile#collections
    get 'collections', to: 'profiles#collections', as: 'collections_page'
    # 我的追蹤的使用者
    # my_following_page   GET    /my/following(.:format)            my/profile#following
    get 'following', to: 'profiles#following', as: 'following_page'
  end
  
end

app/views/pages/shared/_pages-left.html.erb
<!-- pages左側欄位 -->
<section class="column is-2 mt-4">
    <!-- 最新文章（首頁） 按文章建立時間 排序 顯示 所有已發佈文章-->
    <%= link_to root_path do %>
        <div class="text-white text-lg mb-3">
            <i class="fa-solid fa-newspaper mr-3"></i><span>最新文章</span>
        </div>
    <% end %>

    <!-- 熱門文章 按文章愛心數 排序 顯示 所有已發佈文章-->
    <%= link_to hot_page_path do %>
        <div class="text-white text-lg mb-3">
            <i class="fa-solid fa-fire mr-3"></i><span>熱門文章</span>
        </div>
    <% end %>

    <!-- 創作者列表 按帳號建立順序 排序 使用者 -->
    <%= link_to rank_page_path do %>
        <div class="text-white text-lg mb-3">
            <!-- <i class="fa-solid fa-award mr-3"></i> -->
            <i class="fa-solid fa-pen-nib mr-2"></i><span>創作者列表</span>
        </div>
    <% end %>
</section>

app/views/pages/shared/_pages-right.html.erb
<!-- pages右側欄位-廣告 -->
<section class="column is-3">
    <img src="https://fakeimg.pl/300/?retina=1&text=廣告&font=noto" class="mb-2.5 mt-1">
    <img src="https://fakeimg.pl/300/?retina=1&text=廣告&font=noto" class="mb-2.5">
    <img src="https://fakeimg.pl/300x600/?retina=1&text=廣告&font=noto" class="mb-2.5">
</section>

app/views/pages/shared/_published-posts-list.html.erb
<!-- 已發佈文章列表 -->
    <hr class="h-px my-5 bg-gray-200 border-0 dark:bg-gray-700">
    <% if @posts.count == 0 %> <!-- 若整個論壇 已發佈 文章數量 為0的話 -->
        <div class="text-center my-28">
            <p class="text-xl">這個論壇還沒有任何人發佈文章，趕快來寫第一篇吧!</p>
            <%= link_to '建立文章', new_post_path, class:'button bgc-light-blue text-white mt-4' %>
        </div>
    <% else %> <!-- 若整個論壇 已發佈 文章數量 不為0的話 -->
        <% @posts.each do |post| %>
            <div class="media">
                <figure class="media-left mr-2">
                    <!-- <img src="https://fakeimg.pl/25x25/" class="avatar"> -->
                    <!-- 有上傳頭貼 顯示上傳的頭貼，沒頭貼 顯示灰頭 -->
                    <% if post.user.avatar.attached? %>
                        <%= image_tag post.user.avatar.variant(resize_to_fill: [25, 25]), class: 'avatar' %>
                    <% else %>
                        <i class="fa-solid fa-circle-user text-gray-500 text-2xl"></i>
                    <% end %>
                </figure>
                <div class="media-content">
                    <!-- ID -->
                    <span class="text-gray-500">@<%= link_to post.user.username, user_page_path(post.user.username) %></span>
                    <!-- 點擊 ID或卡稱 進入 單一使用者文章列表 -->

                    <!-- 有卡稱 顯示卡稱，沒卡稱 就不顯示 -->
                    <span>
                        <% if post.user.cardname !=nil %>
                            <span class="text-gray-500">・<%= link_to post.user.cardname, user_page_path(post.user.username) %></span>
                        <% else %>
                        <% end %>
                    </span>
                    <span class="text-gray-500">・<%= time_ago_in_words(post.created_at) %></span>
                </div>
            </div>

            <!-- 有上傳封面照片就顯示 照片和內文，沒上傳就只顯示內文 -->
            <% if post.cover_image.attached? %>
                <div class="columns">
                    <div class="column is-10">
                        <span class="text-xl font-bold pb-6"><%= link_to post.title, post_page_path(post.user.username, post) %></span>
                        <!-- 點擊文章標題 進入單篇文章頁面 -->
                        <p><%= strip_tags(post.content).truncate(70) %></p>
                        <!-- strip_tags 拔掉html標籤 truncate截短文字 -->
                    </div>
                    <div class="column is-2">
                        <!-- <img src="https://fakeimg.pl/150/" class="rounded-xl"> -->
                        <%= image_tag post.cover_image.variant(resize_to_fill: [150, 150]), class:'rounded-xl' %>
                        <!-- 將影像縮放至填滿指定尺寸，同時保留原始長寬比。必要時，將在較大的尺寸上裁剪影像。 -->
                    </div>
                </div>
            <% else %>
                <span class="text-xl font-bold pb-6"><%= link_to post.title, post_page_path(post.user.username, post) %></span>
                <p><%= strip_tags(post.content).truncate(70) %></p>
            <% end %>



            <div class="mt-2.5 mb-2">
                <i class="fa-brands fa-gratipay text-rose-400 mr-0.5"></i>
                <span class="text-gray-400 mr-4"><%= post.love %></span>
                <i class="fa-solid fa-comment text-gray-400 mr-0.5"></i>
                <span class="text-gray-400 mr-4"><%= post.comments.count %></span>
                <i class="fa-solid fa-bookmark text-sky-500 mr-0.5"></i>
                <span class="text-gray-400 mr-4"><%= post.bookmarks.count %></span>
            </div>
            <hr class="h-px my-5 bg-gray-200 border-0 dark:bg-gray-700">
        <% end %>
    <% end %>