config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # devise_for :users #devise幫你長出來的 會自動對應該對應的controller

  # 有自己生成controller（rails g devise:controllers 資料夾名稱），客製化的部分要來此設定
  devise_for :users, controllers: {
    registrations: 'users/registrations' # 有關會員註冊（註冊及編輯資料）的controller 請使用users資料夾下的registrations_controlle.rb
  }

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # 首頁：不分類所有已發佈文章列表
  # Defines the root path route ("/")
  root "pages#index"

  # 文章CRUD
  resources :posts do
    # 文章留言
    # /posts/:post_id/comments/:id
    resources :comments, only: [:create, :edit, :update, :destroy]
    # post_comments     POST   /posts/:post_id/comments(.:format)                  comments#create
    # edit_post_comment GET    /posts/:post_id/comments/:id/edit(.:format)         comments#edit
    # post_comment      PATCH  /posts/:post_id/comments/:id(.:format)              comments#update
    #                   PUT    /posts/:post_id/comments/:id(.:format)              comments#update
    # post_comment      DELETE /posts/:post_id/comments/:id(.:format)              comments#destroy
  end

  # 單篇文章頁面
  # /@ID/文章標題-123
  # post_page    GET    /@:username/:post_id(.:format)        pages#show
  get '@:username/:post_id', to: 'pages#show', as: 'post_page'
  # prefix設定為 post_page（不設定就沒有prefix可以用）
  # 不想額外生一個controller，所以就指定用pages controller
  # :username 是符號，冒號不會出現在網址

  # 單一使用者文章列表
  # /@ID
  # user_page   GET    /@:username(.:format)           pages#user
  get '@:username', to: 'pages#user', as: 'user_page'

  # 熱門文章
  # hot_page   GET    /hot(.:format)              pages#hot
  get 'hot', to: 'pages#hot', as: 'hot_page'

  # 創作者排行榜
  # rank_page   GET    /rank(.:format)      pages#rank
  get 'rank', to: 'pages#rank', as: 'rank_page'

  # api相關路徑
  namespace :api do
    namespace :v1 do

      # 追蹤使用者功能 的 api
      # follow_api_v1_user    POST   /api/v1/users/:id/follow(.:format)       api/v1/users#follow
      resources :users, only: [] do
      # 想要網址帶users 但users的CRUD都被devise做完，所以這裡給空陣列，單純用來生成 追蹤使用者功能 的 api路徑
        member do
          post :follow
        end
      end

      resources :posts, only: [] do
        member do
          # 為文章按愛心功能 的 api
          # love_api_v1_post   POST   /api/v1/posts/:id/love(.:format)    api/v1/posts#love
          post :love
          # 收藏文章功能 的 api
          # bookmark_api_v1_post    POST   /api/v1/posts/:id/bookmark(.:format)      api/v1/posts#bookmark
          post :bookmark
        end
      end

      # 用Froala editor上傳圖片功能 的 api
      # api_v1_upload_image    POST   /api/v1/upload_image(.:format)        api/v1/utils#upload_image
      post :upload_image, to: 'utils#upload_image'

    end
  end

  namespace :my do
    # 個人資料首頁：我的收藏
    # my_root   GET    /my(.:format     my/profile#collections
    root 'profiles#collections'
    # 我的收藏
    # my_collections_page    GET    /my/collections(.:format)           my/profile#collections
    get 'collections', to: 'profiles#collections', as: 'collections_page'
    # 我的追蹤的使用者
    # my_following_page   GET    /my/following(.:format)            my/profile#following
    get 'following', to: 'profiles#following', as: 'following_page'
  end
  
end

app/views/shared/_flash.html.erb
<div class="notification mb-0">
    <button class="delete"></button>
    <%= notice %>
</div>

<script> 
    // Step 1: Select all the delete buttons which are inside notification element  
    // and loop over them using forEach 
    document.querySelectorAll(".notification .delete") 
        .forEach(function ($deleteButton) { 

            // Step 2: Get the parent notification of the delete button 
            const parentNotification = $deleteButton.parentNode; 

            // Add click event listener on delete button and when the button get clicked 
            // remove the parent notification 
            $deleteButton.addEventListener('click', function () { 
                parentNotification.parentNode 
                    .removeChild(parentNotification); 
            }); 
        }); 
</script> 

app/views/shared/_navbar.html.erb
<div class="bgc-medium-blue pb-3">
  <nav class="navbar is-link max-w-7xl mx-auto" role="navigation" aria-label="main navigation">
    <!-- bulma藍底白字導覽列 再用自己寫的css蓋掉底色 -->

        <div class="navbar-brand bgc-medium-blue">

          <%= link_to root_path, class: "navbar-item" do%>
            <h1 class="text-2xl font-mono font-bold text-white mr-5">Bcard</h1>
          <% end %>
      
          <!-- 漢堡選單 -->
          <a role="button" class="navbar-burger" data-target="navMenu" aria-label="menu" aria-expanded="false">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
          </a>

        </div>
      
        <div id="navbarBasicExample" class="navbar-menu bgc-medium-blue">
          <div class="navbar-start">
    
            <div class="control">
                <input class="input mt-3 w-96" type="text" placeholder="搜尋 熱門文章">
            </div>
            <div class="control">
                <button class="button is-medium mt-3 border-1 border-blue-800 text-white bgc-medium-blue ">
                  <i class="fa-solid fa-magnifying-glass"></i>
                </button>
            </div>
          </div>
      
          <div class="navbar-end">
            <div class="navbar-item">
              <div class="buttons">
                <% if user_signed_in? %> <!-- 有登入的話 -->
                  <!-- 新增文章 筆（點了會進 新增文章表單頁面） -->
                  <%=link_to new_post_path do %>
                    <i class="fa-solid fa-pen text-white text-xl mr-4"></i>
                  <% end %>
                  
                  <!-- 個人資訊小人(點了會進個人資料首頁 我的收藏文章) -->
                  <%=link_to my_root_path do %>
                    <i class="fa-solid fa-user text-white text-xl"></i>
                  <% end %>
    
                  
                  <div class="navbar-item has-dropdown is-hoverable is-dark">
                    <a class="navbar-link">
                      <!-- <i class="fa-solid fa-caret-down text-white mr-3"></i> -->
                    </a>
            
                    <div class="navbar-dropdown">
                      <a class="navbar-item">
                        服務條款
                      </a>
                      <a class="navbar-item">
                        幫助中心
                      </a>
                      <a class="navbar-item">
                        聯繫我們
                      </a>
                      <!-- <hr class="navbar-divider"> -->
                      <a class="navbar-item">
                        品牌識別
                      </a>
                      <a class="navbar-item">
                        徵才
                      </a>
                      <a class="navbar-item">
                        商業合作
                      </a>
                      <a class="navbar-item">
                        免費下載 App
                      </a>
                    </div>
                  </div>
              
    
                  <%=link_to "登出", destroy_user_session_path, class: 'button is-info mt-1 text-white bgc-light-blue', data: {turbo_method: :delete, turbo_confirm: "確定登出？"} %>
                </div>
                <% else %> <!-- 沒登入的話 -->
    
                  <%=link_to "註冊", new_user_registration_path, class: 'button is-info mt-1 text-white bgc-light-blue' %>
                  <%=link_to "登入", new_user_session_path, class: 'button is-info mt-1 text-white bgc-light-blue' %>
                  
                <% end %>
              </div>
          </div>
        </div>
  </nav>
</div>

app/views/shared/_profile-left.html.erb
<section class="column is-3">
    <div class="w-fit m-auto">
        <!-- <img src="https://fakeimg.pl/100x100/" class="avatar my-5"> -->
        <div class="avatar my-5">
            <!-- <%= avatar(current_user, 100)%> -->
            <% if current_user.avatar.attached? %>
                <%= image_tag current_user.avatar.variant(resize_to_fill: [100, 100]), class: 'avatar' %>
            <% else %>
                <i class="fa-solid fa-circle-user text-white text-8xl"></i>
            <% end %>
        </div>
    </div>
    <p class="text-white text-2xl font-semibold text-center mb-1"><%= current_user.cardname %></p>
    <p class="text-gray-400 text-center mb-4">@<%= current_user.username %></p>
    <div class="w-fit mx-auto">
        <%= link_to '#' do %>
            <i class="fa-solid fa-bookmark text-sky-600 text-xl ml-0.5 mr-2.5 mb-3"></i>
            <span class="text-white">我的收藏</span>
        <% end %><br>
        <%= link_to '#' do %>
            <i class="fa-solid fa-heart text-rose-500 text-xl mr-1.5 mb-3"></i>
            <span class="text-white">我追蹤的卡稱</span>
        <% end %><br>
        <%= link_to posts_path do %>
            <i class="fa-solid fa-square-pen text-sky-600 text-xl mr-2 mb-3"></i>
            <span class="text-white">我的文章</span>
        <% end %><br>
        <%= link_to edit_user_registration_path  do %>
            <i class="fa-solid fa-gear text-white text-xl mr-1.5 mb-3 "></i>
            <span class="text-white">我的個人資料</span>
        <% end %>
    </div>
</section>