config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # devise_for :users #devise幫你長出來的 會自動對應該對應的controller

  # 有自己生成controller（rails g devise:controllers 資料夾名稱），客製化的部分要來此設定
  devise_for :users, controllers: {
    registrations: 'users/registrations' # 有關會員註冊（註冊及編輯資料）的controller 請使用users資料夾下的registrations_controlle.rb
  }

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # 首頁：不分類所有已發佈文章列表
  # Defines the root path route ("/")
  root "pages#index"

  # 文章CRUD
  resources :posts do
    # 文章留言
    # /posts/:post_id/comments/:id
    resources :comments, only: [:create, :edit, :update, :destroy]
    # post_comments     POST   /posts/:post_id/comments(.:format)                  comments#create
    # edit_post_comment GET    /posts/:post_id/comments/:id/edit(.:format)         comments#edit
    # post_comment      PATCH  /posts/:post_id/comments/:id(.:format)              comments#update
    #                   PUT    /posts/:post_id/comments/:id(.:format)              comments#update
    # post_comment      DELETE /posts/:post_id/comments/:id(.:format)              comments#destroy
  end

  # 單篇文章頁面
  # /@ID/文章標題-123
  # post_page    GET    /@:username/:post_id(.:format)        pages#show
  get '@:username/:post_id', to: 'pages#show', as: 'post_page'
  # prefix設定為 post_page（不設定就沒有prefix可以用）
  # 不想額外生一個controller，所以就指定用pages controller
  # :username 是符號，冒號不會出現在網址

  # 單一使用者文章列表
  # /@ID
  # user_page   GET    /@:username(.:format)           pages#user
  get '@:username', to: 'pages#user', as: 'user_page'

  # 熱門文章
  # hot_page   GET    /hot(.:format)              pages#hot
  get 'hot', to: 'pages#hot', as: 'hot_page'

  # 創作者排行榜
  # rank_page   GET    /rank(.:format)      pages#rank
  get 'rank', to: 'pages#rank', as: 'rank_page'

  # api相關路徑
  namespace :api do
    namespace :v1 do

      # 追蹤使用者功能 的 api
      # follow_api_v1_user    POST   /api/v1/users/:id/follow(.:format)       api/v1/users#follow
      resources :users, only: [] do
      # 想要網址帶users 但users的CRUD都被devise做完，所以這裡給空陣列，單純用來生成 追蹤使用者功能 的 api路徑
        member do
          post :follow
        end
      end

      resources :posts, only: [] do
        member do
          # 為文章按愛心功能 的 api
          # love_api_v1_post   POST   /api/v1/posts/:id/love(.:format)    api/v1/posts#love
          post :love
          # 收藏文章功能 的 api
          # bookmark_api_v1_post    POST   /api/v1/posts/:id/bookmark(.:format)      api/v1/posts#bookmark
          post :bookmark
        end
      end

      # 用Froala editor上傳圖片功能 的 api
      # api_v1_upload_image    POST   /api/v1/upload_image(.:format)        api/v1/utils#upload_image
      post :upload_image, to: 'utils#upload_image'

    end
  end

  namespace :my do
    # 個人資料首頁：我的收藏
    # my_root   GET    /my(.:format     my/profile#collections
    root 'profiles#collections'
    # 我的收藏
    # my_collections_page    GET    /my/collections(.:format)           my/profile#collections
    get 'collections', to: 'profiles#collections', as: 'collections_page'
    # 我的追蹤的使用者
    # my_following_page   GET    /my/following(.:format)            my/profile#following
    get 'following', to: 'profiles#following', as: 'following_page'
  end
  
end

app/views/pages/_comment.html.erb
<!-- 所有留言區 -->
<article class="comment">
    <hr class="h-px my-3 bg-gray-200 border-0 dark:bg-gray-700">
    <section class="columns">
        <section class="column is-10">
            <article class="media">
                <figure class="media-left">
                    <!-- 有上傳頭貼 顯示上傳的頭貼，沒頭貼 顯示灰頭 -->
                    <!-- <img src="https://fakeimg.pl/50x50/" class="avatar"> -->
                    <% if comment.user.avatar.attached? %>
                        <%= image_tag comment.user.avatar.variant(resize_to_fill: [50, 50]), class: 'avatar' %>
                    <% else %>
                        <i class="fa-solid fa-circle-user text-gray-500 text-5xl"></i>
                    <% end %>
                </figure>
                
                <div class="media-content">
                    <!-- 有卡稱 顯示卡稱+ID，沒卡稱 就只顯示ID -->
                    <% if comment.user.cardname != nil %>
                        <%= link_to comment.user.cardname, user_page_path(comment.user.username) %><br>
                        <%= link_to "@#{comment.user.username}", user_page_path(comment.user.username), class:'text-gray-400 text-sm' %>
                    <% else %>
                        <%= link_to user_page_path(comment.user.username) do %>
                            <div class="text-gray-600 pt-2.5">@<%= comment.user.username %></div>
                        <% end %>
                    <% end %>                                
                </div>
            </article>
        </section>
        <!-- 自己的留言才顯示 編輯、刪除 -->
        <% if comment.user == current_user %>
            <section class="column is-2 text-right mt-2">
                <%= link_to edit_post_comment_path(comment.post, comment) do %>
                <!-- edit_post_comment GET    /posts/:post_id/comments/:id/edit(.:format)         comments#edit -->
                    <i class="fa-solid fa-pen mr-2 text-gray-400"></i>
                <% end %>
                <%= link_to post_comment_path(comment.post, comment), data: {turbo_method: :delete, turbo_confirm: "確定刪除此留言？"}  do %>
                <!-- post_comment      DELETE /posts/:post_id/comments/:id(.:format)              comments#destroy -->
                    <i class="fa-solid fa-trash-can text-gray-400"></i>
                <% end %>
            </section>
        <% else %>
        <% end %>
    </section>

    <div class="ml-16">
        <article class="mb-7">
            <p><%= simple_format(comment.content, class: 'description') %></p>
        </article>
        <p class="text-gray-400 text-sm mb-1.5"><%= comment.created_at.strftime("%Y年%m月%d日 %I:%M") %></p>
    </div>
</article>

app/views/pages/_comment_input.html.erb
<% if user_signed_in? %> <!-- 使用者有登入才出現留言輸入區塊 -->

    <article class="media mt-5">
        <figure class="media-left">
            <!-- 有上傳頭貼 顯示上傳的頭貼，沒頭貼 顯示灰頭 -->
            <!-- <img src="https://fakeimg.pl/50x50/" class="avatar"> -->
            <% if current_user.avatar.attached? %>
                <%= image_tag current_user.avatar.variant(resize_to_fill: [50, 50]), class: 'avatar' %>
            <% else %>
                <i class="fa-solid fa-circle-user text-gray-500 text-5xl"></i>
            <% end %>
        </figure>

        <div class="media-content">
            <!-- ID -->
            <span class="text-gray-600">@<%= current_user.username %></span>
            <!-- 有卡稱 顯示卡稱，沒卡稱 就不顯示 -->
            <span>
                <% if current_user.cardname !=nil %>
                    <span>・<%= current_user.cardname %></span>
                <% else %>
                <% end %>
            </span>
            <p class="text-gray-400 text-sm mb-1.5"><%= Time.current.strftime("%Y年%m月%d日 %I:%M") %></p>
            <!-- https://khiav223577.github.io/blog/2018/03/03/Rails-%E4%B8%AD%E5%B8%B8%E6%90%9E%E6%B7%B7%E7%9A%84%E6%99%82%E5%8D%80%E5%95%8F%E9%A1%8C-Time-now-vs-Time-current/ -->
            <!-- Time.now 使用當前機器作業系統的時區；Time.current 使用 Rails 中設定的時區 -->
        </div>
    </article>

    <%= form_with model: comment, url: post_comments_path(post), class: 'comment_form', remote: true, data: {turbo: true}  do |form| %>
        <%= form.text_area :content, rows: 5, class: 'textarea' %>
        <div class="text-right">
            <%= form.submit "送出", class: 'button bgc-light-blue text-white my-2' %>
            <!-- form.button "送出", class: 'button bgc-light-blue text-white my-2' -->
        </div>
    <% end %>

<% else %> <!-- 沒登入的話 -->

    <p class="text-xl font-bold text-center">登入後即可一起討論喔！</p>
    <div class="text-center mt-2 mb-4">
        <%= link_to '註冊', new_user_registration_path, class:'button bgc-light-blue text-white' %>
        <%= link_to "登入", new_user_session_path, class: 'button bgc-light-blue text-white' %>

    </div>
<% end %>

app/views/pages/hot.html.erb
<!-- 熱門文章 -->
<div class="bgc-dark-blue min-h-screen">
    <section class="columns max-w-7xl mx-auto">

        <!-- 左側欄位 -->
        <%= render 'pages/shared/pages-left' %>

        <!-- 中間欄位-已發佈文章列表（按文章愛心數順序顯示） -->
        <section class="column is-7 bg-white my-4 rounded p-14">
            <h1 class="text-2xl font-semibold">熱門文章</h1>
            <%= render 'pages/shared/published-posts-list' %>
        </section>

        <!-- 右側欄位-廣告 -->
        <%= render 'pages/shared/pages-right' %>

    </section>
</div>

app/views/pages/index.html.erb
<!-- 首頁 -->
<div class="bgc-dark-blue min-h-screen">
    <section class="columns max-w-7xl mx-auto">

        <!-- 左側欄位 -->
        <%= render 'pages/shared/pages-left' %>

        <!-- 中間欄位-已發佈文章列表（按文章建立順序顯示） -->
        <section class="column is-7 bg-white my-4 rounded p-14">
            <h1 class="text-2xl font-semibold">最新文章</h1>
            <%= render 'pages/shared/published-posts-list' %>
        </section>

        <!-- 右側欄位-廣告 -->
        <%= render 'pages/shared/pages-right' %>

    </section>
</div>

app/views/pages/rank.html.erb
<!-- 創作者列表 -->
<div class="bgc-dark-blue min-h-screen">
    <section class="columns max-w-7xl mx-auto">

        <!-- 左側欄位 -->
        <%= render 'pages/shared/pages-left' %>

        <!-- 中間欄位-創作者列表 -->
        <section class="column is-7 bg-white my-4 rounded p-14">
            <h1 class="text-2xl font-semibold">創作者列表</h1>
            <hr class="h-px my-5 bg-gray-200 border-0 dark:bg-gray-700">
            <% if @ranks.count == 0 %> <!-- 若論壇 用戶數量 為0的話 -->
                <div class="text-center my-28">
                    <p class="text-xl">這個論壇還沒有任何使用者，趕快來成為第一個會員吧!</p>
                    <%= link_to '註冊', new_user_registration_path, class:'button bgc-light-blue text-white mt-4' %>
                </div>
            <% else %> <!-- 若論壇 用戶數量 不為0的話 -->
                <% @ranks.each do |user| %>
                    <section class="columns">
                        <section class="column is-1">
                            <!-- <i class="fa-solid fa-crown text-yellow-500 text-xl pt-8"></i> -->
                            <i class="fa-solid fa-pen-nib text-gray-500 text-xl pt-9"></i>
                        </section>
                        <section class="column is-6">
                            <article class="media mt-5">
                                <figure class="media-left">
                                    <!-- 有上傳頭貼 顯示上傳的頭貼，沒頭貼 顯示灰頭 -->
                                    <!-- <img src="https://fakeimg.pl/50x50/" class="avatar"> -->
                                    <% if user.avatar.attached? %>
                                        <%= image_tag user.avatar.variant(resize_to_fill: [50, 50]), class: 'avatar' %>
                                    <% else %>
                                        <i class="fa-solid fa-circle-user text-gray-500 text-5xl"></i>
                                    <% end %>
                                </figure>
                                <div class="media-content">
                                    <!-- 有卡稱 顯示卡稱+ID，沒卡稱 就只顯示ID -->
                                    <% if user.cardname != nil %>
                                        <%= link_to user.cardname, user_page_path(user.username) %><br>
                                        <%= link_to "@#{user.username}", user_page_path(user.username), class:'text-gray-400 text-sm' %>
                                    <% else %>
                                        <%= link_to user_page_path(user.username) do %>
                                            <div class="text-gray-600 pt-2.5">@<%= user.username %></div>
                                        <% end %>
                                    <% end %>                                
                                </div>
                            </article>
                        </section>
                        <section class="column is-5" data-controller="user">
                            <%= link_to '#', data: { action: "user#followBig", user: user.id } do %>
                                <% if user_signed_in? && current_user.follow?(user) %>
                                    <div class="text-right">
                                        <span class="button mt-5 bg-gray-300 hover:bg-white" data-user-target="followButtonBig" >
                                            追蹤中
                                        </span>
                                    </div>
                                <% else %>
                                    <div class="text-right">
                                        <span class="button mt-5 bgc-light-blue text-white hover:bg-sky-400" data-user-target="followButtonBig" >
                                            追蹤
                                        </span>
                                    </div>
                                <% end %>
                            <% end %>
                        </section>
                    </section>
                <% end %>
            <% end %>
        </section>

        <!-- 右側欄位-廣告 -->
        <%= render 'pages/shared/pages-right' %>

    </section>
</div>

app/views/pages/show.html.erb
<!-- 單一文章頁面 -->
<div class="bgc-dark-blue min-h-screen">
    <section class="columns max-w-3xl mx-auto">
        <section class="column is-12 bg-neutral-100 my-4 rounded p-14">
            <div class="text-3xl font-bold mb-4"><%= @post.title %></div>
            <!-- <div class="text-3xl font-bold"><= link_to post.title, post_page_path(post.user.username, post) %></div> -->
            <section class="columns" data-controller="user">
                <section class="column is-10">
                    <article class="media">
                        <figure class="media-left mr-2">
                            <!-- <img src="https://fakeimg.pl/25x25/" class="avatar"> -->
                            <!-- 有上傳頭貼 顯示上傳的頭貼，沒頭貼 顯示灰頭 -->
                            <% if @post.user.avatar.attached? %>
                                <%= image_tag @post.user.avatar.variant(resize_to_fill: [25, 25]), class: 'avatar' %>
                            <% else %>
                                <i class="fa-solid fa-circle-user text-gray-500 text-2xl"></i>
                            <% end %>
                        </figure>
                        <div class="media-content">
                            <!-- ID -->
                            <span class="text-gray-500">@<%= link_to @post.user.username, user_page_path(@post.user.username) %></span>

                            <!-- 有卡稱 顯示卡稱，沒卡稱 就不顯示 -->
                            <span>
                                <% if @post.user.cardname != nil %>
                                    <span class="text-gray-500">・<%= link_to @post.user.cardname, user_page_path(@post.user.username) %></span>
                                <% else %>
                                <% end %>
                            </span>

                            <span class="text-gray-500">・</span>
                            <%= link_to '#', data: { action: "user#follow", user: @post.user.id } do %>
                                <!-- <span class="followButton text-sky-500 hover:text-sky-400" data-user-target="followButton">
                                    <= (user_signed_in? && current_user.follow?(@post.user))? '追蹤中' : '追蹤' %>
                                </span> -->
                                <span data-user-target="followButton">
                                    <% if user_signed_in? && current_user.follow?(@post.user) %>
                                        <span class="followButton text-gray-500 hover:text-gray-400" >
                                            追蹤中
                                        </span>
                                    <% else %>
                                        <span class="followButton text-sky-500 hover:text-sky-400" >
                                            追蹤
                                        </span>
                                    <% end %>
                                </span>
                            <% end %>
                            <span class="text-gray-500">・<%= @post.created_at.strftime("%Y年%m月%d日 %I:%M") %></span>
                        </div>
                    </article>
                </section>
                <!-- 自己的文章才顯示 編輯、刪除 按鈕-->
                <% if @post.user == current_user %>
                    <section class="column is-2 text-right">
                        <%= link_to edit_post_path(@post) do %>
                            <i class="fa-solid fa-pen mr-2 text-gray-400"></i>
                        <% end %>
                        <%= link_to post_path(@post), data: {turbo_method: :delete, turbo_confirm: "確定刪除此文章？"}  do %>
                            <i class="fa-solid fa-trash-can text-gray-400"></i>
                        <% end %>
                    </section>
                <% else %>
                <% end %>
            </section>

            <div class="w-fit mx-auto mb-2">
                <%= image_tag @post.cover_image.variant(resize_to_limit: [640, nil]) if @post.cover_image.attached? %>
                <!-- 將影像縮小到符合指定尺寸，同時保留原始長寬比。僅當影像大於指定尺寸時才會縮放影像。 -->
            </div>

            <p><%= @post.content.html_safe %></p>

            <footer class="mt-7 mb-5" data-controller="post">
                <%= link_to "#", data: { action:"post#addLove", slug: @post.slug } do %>
                <!--  slug: @post.slug為哪一篇文章按愛心 要在哪一篇文章資料的愛心欄位加數字 -->
                <!--  <a data-action="post#addLove" data-slug="文章標題" href="#"> -->
                    <i class="loveButton fa-brands fa-gratipay text-rose-400 mr-0.5 text-2xl hover:text-rose-500"></i>
                <% end %>
                <span class="loveCount text-gray-500 text-xl" data-post-target="loveCount"><%= @post.love %></span>
                <span class="text-gray-500 text-xl">・</span>
                <i class="fa-solid fa-comment text-gray-400 text-2xl mr-1"></i>
                <span class="text-gray-500 text-xl"><%= @post.comments.count %></span>
                <span class="text-gray-500 text-xl">・</span>

                <%= link_to "#", data: { action:"post#bookmark", slug: @post.slug } do %>
                <!--  slug: @post.slug要收藏哪一篇文章 -->
                <!--  <a data-action="post#bookmark" data-slug="文章標題" href="#"> -->
                    <% if user_signed_in? && @post.bookmark?(current_user) %>
                        <i class="bookmarkButton fa-solid fa-bookmark text-sky-500 text-2xl mr-1" data-post-target="bookmark"></i>
                    <% else %>
                        <i class="bookmarkButton fa-solid fa-bookmark text-gray-400 text-2xl mr-1 hover:text-sky-500" data-post-target="bookmark"></i>
                    <% end %>
                <% end %>
                <span class="text-gray-500 text-xl" data-post-target="bookmarkCount"><%= @post.bookmarks.count %></span>

            </footer>

            <div class="text-gray-500">共 <%= @post.comments.count %> 則留言</div>
            <hr class="h-px my-2 bg-gray-200 border-0 dark:bg-gray-700">
          
            <!-- 留言輸入區 -->
            <%= render 'comment_input', post: @post, comment: @comment %>

            <!-- 所有留言區 -->
            <section class="comment-list">
                <%= render partial: 'comment', collection: @comments %>
            </section>

        </section>
    </section>
</div>

app/views/pages/user.html.erb
<!-- 個人頁面（單一使用者文章列表） -->
<div class="bgc-dark-blue min-h-screen">
    <section class="columns max-w-3xl mx-auto">
        <section class="column is-12 bg-neutral-100 my-4 rounded p-14">
            <div>
                <!-- 頭貼 -->
                <% if @user.avatar.attached? %>
                    <%= image_tag @user.avatar.variant(resize_to_fill: [150, 150]), class: 'avatar' %>
                <% else %>
                    <i class="fa-solid fa-circle-user text-gray-500 text-9xl"></i>
                <% end %>
            </div>
            <div class="columns">
                <div class="column">
                    <!-- 有卡稱 顯示卡稱+ID，沒卡稱 就只顯示ID -->
                    <% if @user.cardname != nil %>
                        <div class="text-lg font-bold mt-2"><%= @user.cardname %></div>
                        <div class="text-gray-400">@<%= @user.username %></div>
                    <% else %>
                        <div class="text-lg mt-2">@<%= @user.username %></div>
                    <% end %> 
                    <span class="text-gray-400"><%= @user.posts.published.count %>篇已發佈文章</span>
                    <span class="text-gray-400">・正在追蹤<%= @user.follows.count %>人</span>
                    <span data-controller="user">
                        <span class="text-gray-400">・</span>
                        <span class="text-gray-400" data-user-target="followCount"><%= @follow_count %></span>
                        <span class="text-gray-400">位粉絲</span>
                    </span>
                </div>
                <div class="column text-right" data-controller="user">
                    <%= link_to '#', data: { action: "user#followBig", user: @user.id } do %>
                        <% if user_signed_in? && current_user.follow?(@user) %>
                            <span class="button mt-5 bg-gray-300 hover:bg-white" data-user-target="followButtonBig" >
                                追蹤中
                            </span>
                        <% else %>
                            <span class="button mt-5 bgc-light-blue text-white hover:bg-sky-400" data-user-target="followButtonBig" >
                                追蹤
                            </span>
                        <% end %>
                    <% end %>
                </div>
            </div>
            <div class="text-gray-500 mb-2">
                <%= @user.intro %>
            </div>
            <hr class="h-px my-5 bg-gray-200 border-0 dark:bg-gray-700">

            <% if @user.posts.published.count == 0 %>
                <div class="text-lg text-gray-500 text-center">該使用者目前無已發佈文章！</div>
            <% else %>
                <% @posts.each do |post| %>
                    <p class="text-gray-500 text-sm mb-1.5"><%= post.created_at.strftime("%Y年%m月%d日") %></p>
                    <div class="bg-white rounded-xl p-5 mb-5">
                        <div class="bg-white rounded-xl p-5 mb-5">
                            <section class="columns mb-0">
                                <section class="column is-12">
                                    <article class="media">
                                        <figure class="media-left mr-2">
                                            <!-- <img src="https://fakeimg.pl/25x25/" class="avatar"> -->
                                            <!-- 有上傳頭貼 顯示上傳的頭貼，沒頭貼 顯示灰頭 -->
                                            <% if post.user.avatar.attached? %>
                                                <%= image_tag post.user.avatar.variant(resize_to_fill: [25, 25]), class: 'avatar' %>  
                                            <% else %>  
                                                <i class="fa-solid fa-circle-user text-gray-500 text-2xl"></i>
                                            <% end %>   
                                        </figure>
                                        <div class="media-content">
                                            <!-- ID -->
                                            <span class="text-gray-500">@<%= post.user.username %></span>
                                            <!-- 有卡稱 顯示卡稱，沒卡稱 就不顯示 -->
                                            <span>
                                                <% if post.user.cardname !=nil %>
                                                    <span class="text-gray-500">・<%= post.user.cardname %></span>
                                                <% else %>
                                                <% end %> 
                                            </span>
                                        </div>
                                    </article>
                                </section>
                            </section>
                            <!-- 有上傳封面照片就顯示 照片和內文，沒上傳就只顯示內文 -->
                            <% if post.cover_image.attached? %>
                                <div class="columns">
                                    <div class="column is-10">
                                        <span class="text-xl font-bold"><%= link_to post.title, post_page_path(post.user.username, post) %></span>
                                        <p><%= strip_tags(post.content).truncate(60) %></p>
                                    </div>
                                    <div class="column is-2">
                                        <%= image_tag post.cover_image.variant(resize_to_fill: [150, 150]), class:'rounded-xl' %>
                                    </div>
                                </div>
                            <% else %>
                                <span class="text-xl font-bold"><%= link_to post.title, post_page_path(post.user.username, post) %></span>
                                <p><%= strip_tags(post.content).truncate(60) %></p>
                            <% end %>

                            <div class="mt-2.5">
                                <i class="fa-brands fa-gratipay text-rose-400 mr-0.5"></i>
                                <span class="text-gray-400 mr-4"><%= post.love %></span>
                                <i class="fa-solid fa-comment text-gray-400 mr-0.5"></i>
                                <span class="text-gray-400 mr-4"><%= post.comments.count %></span>
                                <i class="fa-solid fa-bookmark text-sky-500 mr-0.5"></i>
                                <span class="text-gray-400 mr-4"><%= post.bookmarks.count %></span>
                            </div>
                        </div>
                    </div>
                <% end %>
            <% end %>
        </section>
    </section>
</div>